# Generated by Django 3.1 on 2020-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=5000)),
                ('con1', models.CharField(default='', max_length=50000)),
                ('head2', models.CharField(default='', max_length=5000)),
                ('con2', models.CharField(default='', max_length=50000)),
                ('head3', models.CharField(default='', max_length=5000)),
                ('con3', models.CharField(default='', max_length=50000)),
                ('head4', models.CharField(default='', max_length=5000)),
                ('con4', models.CharField(default='', max_length=50000)),
                ('timeStemp', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField()),
                ('summary', models.CharField(default='', max_length=50000)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('image1', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
