# Generated by Django 3.1 on 2020-08-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200827_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='con2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='con3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='con4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
