# Generated by Django 3.1 on 2020-08-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
