# Generated by Django 3.1 on 2020-08-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
